// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/atx.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_FIBER                Category = 1
	Category_LAN                  Category = 2
	Category_ROUTERS              Category = 3
	Category_SWITCHES             Category = 4
	Category_CONNECTORS           Category = 5
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "FIBER",
		2: "LAN",
		3: "ROUTERS",
		4: "SWITCHES",
		5: "CONNECTORS",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"FIBER":                1,
		"LAN":                  2,
		"ROUTERS":              3,
		"SWITCHES":             4,
		"CONNECTORS":           5,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_atx_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_proto_atx_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{0}
}

type Unit int32

const (
	Unit_UNIT_UNSPECIFIED Unit = 0
	Unit_METRES           Unit = 1
	Unit_PIECES           Unit = 2
	Unit_BOXES            Unit = 3
	Unit_ROLLS            Unit = 4
)

// Enum value maps for Unit.
var (
	Unit_name = map[int32]string{
		0: "UNIT_UNSPECIFIED",
		1: "METRES",
		2: "PIECES",
		3: "BOXES",
		4: "ROLLS",
	}
	Unit_value = map[string]int32{
		"UNIT_UNSPECIFIED": 0,
		"METRES":           1,
		"PIECES":           2,
		"BOXES":            3,
		"ROLLS":            4,
	}
)

func (x Unit) Enum() *Unit {
	p := new(Unit)
	*p = x
	return p
}

func (x Unit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Unit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_atx_proto_enumTypes[1].Descriptor()
}

func (Unit) Type() protoreflect.EnumType {
	return &file_proto_atx_proto_enumTypes[1]
}

func (x Unit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Unit.Descriptor instead.
func (Unit) EnumDescriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{1}
}

type ChangeReason int32

const (
	ChangeReason_REASON_UNSPECIFIED ChangeReason = 0
	ChangeReason_RESTOCK            ChangeReason = 1
	ChangeReason_SALE               ChangeReason = 2
	ChangeReason_DAMAGE             ChangeReason = 3
	ChangeReason_MANUAL_ADJUSTMENT  ChangeReason = 4
)

// Enum value maps for ChangeReason.
var (
	ChangeReason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "RESTOCK",
		2: "SALE",
		3: "DAMAGE",
		4: "MANUAL_ADJUSTMENT",
	}
	ChangeReason_value = map[string]int32{
		"REASON_UNSPECIFIED": 0,
		"RESTOCK":            1,
		"SALE":               2,
		"DAMAGE":             3,
		"MANUAL_ADJUSTMENT":  4,
	}
)

func (x ChangeReason) Enum() *ChangeReason {
	p := new(ChangeReason)
	*p = x
	return p
}

func (x ChangeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_atx_proto_enumTypes[2].Descriptor()
}

func (ChangeReason) Type() protoreflect.EnumType {
	return &file_proto_atx_proto_enumTypes[2]
}

func (x ChangeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeReason.Descriptor instead.
func (ChangeReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{2}
}

type Product struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category          Category               `protobuf:"varint,4,opt,name=category,proto3,enum=Category" json:"category,omitempty"`
	Price             float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock             int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	Unit              Unit                   `protobuf:"varint,7,opt,name=unit,proto3,enum=Unit" json:"unit,omitempty"`
	LowStockThreshold int32                  `protobuf:"varint,8,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_atx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UNIT_UNSPECIFIED
}

func (x *Product) GetLowStockThreshold() int32 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

type StockHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"` // positive = added, negative = removed
	StockAfter    int32                  `protobuf:"varint,3,opt,name=stock_after,json=stockAfter,proto3" json:"stock_after,omitempty"`
	Reason        ChangeReason           `protobuf:"varint,4,opt,name=reason,proto3,enum=ChangeReason" json:"reason,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockHistory) Reset() {
	*x = StockHistory{}
	mi := &file_proto_atx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockHistory) ProtoMessage() {}

func (x *StockHistory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockHistory.ProtoReflect.Descriptor instead.
func (*StockHistory) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{1}
}

func (x *StockHistory) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockHistory) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockHistory) GetStockAfter() int32 {
	if x != nil {
		return x.StockAfter
	}
	return 0
}

func (x *StockHistory) GetReason() ChangeReason {
	if x != nil {
		return x.Reason
	}
	return ChangeReason_REASON_UNSPECIFIED
}

func (x *StockHistory) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *StockHistory) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type AddProductRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category          Category               `protobuf:"varint,3,opt,name=category,proto3,enum=Category" json:"category,omitempty"`
	Price             float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock             int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Unit              Unit                   `protobuf:"varint,6,opt,name=unit,proto3,enum=Unit" json:"unit,omitempty"`
	LowStockThreshold int32                  `protobuf:"varint,7,opt,name=low_stock_threshold,json=lowStockThreshold,proto3" json:"low_stock_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_proto_atx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{2}
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductRequest) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *AddProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddProductRequest) GetUnit() Unit {
	if x != nil {
		return x.Unit
	}
	return Unit_UNIT_UNSPECIFIED
}

func (x *AddProductRequest) GetLowStockThreshold() int32 {
	if x != nil {
		return x.LowStockThreshold
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_atx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reason        ChangeReason           `protobuf:"varint,3,opt,name=reason,proto3,enum=ChangeReason" json:"reason,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_atx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateStockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateStockRequest) GetReason() ChangeReason {
	if x != nil {
		return x.Reason
	}
	return ChangeReason_REASON_UNSPECIFIED
}

func (x *UpdateStockRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_proto_atx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStockHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockHistoryRequest) Reset() {
	*x = GetStockHistoryRequest{}
	mi := &file_proto_atx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockHistoryRequest) ProtoMessage() {}

func (x *GetStockHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetStockHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_proto_atx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{7}
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Product       *Product               `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_proto_atx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{8}
}

func (x *ProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_atx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StockHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	History       []*StockHistory        `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockHistoryResponse) Reset() {
	*x = StockHistoryResponse{}
	mi := &file_proto_atx_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockHistoryResponse) ProtoMessage() {}

func (x *StockHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_atx_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockHistoryResponse.ProtoReflect.Descriptor instead.
func (*StockHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_atx_proto_rawDescGZIP(), []int{10}
}

func (x *StockHistoryResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockHistoryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockHistoryResponse) GetHistory() []*StockHistory {
	if x != nil {
		return x.History
	}
	return nil
}

var File_proto_atx_proto protoreflect.FileDescriptor

const file_proto_atx_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/atx.proto\"\xed\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\bcategory\x18\x04 \x01(\x0e2\t.CategoryR\bcategory\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12\x19\n" +
	"\x04unit\x18\a \x01(\x0e2\x05.UnitR\x04unit\x12.\n" +
	"\x13low_stock_threshold\x18\b \x01(\x05R\x11lowStockThreshold\"\xc3\x01\n" +
	"\fStockHistory\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vstock_after\x18\x03 \x01(\x05R\n" +
	"stockAfter\x12%\n" +
	"\x06reason\x18\x04 \x01(\x0e2\r.ChangeReasonR\x06reason\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"\xe7\x01\n" +
	"\x11AddProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\bcategory\x18\x03 \x01(\x0e2\t.CategoryR\bcategory\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x19\n" +
	"\x04unit\x18\x06 \x01(\x0e2\x05.UnitR\x04unit\x12.\n" +
	"\x13low_stock_threshold\x18\a \x01(\x05R\x11lowStockThreshold\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x12UpdateStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12%\n" +
	"\x06reason\x18\x03 \x01(\x0e2\r.ChangeReasonR\x06reason\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16GetStockHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListProductsRequest\"i\n" +
	"\x0fProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\aproduct\x18\x03 \x01(\v2\b.ProductR\aproduct\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"r\n" +
	"\x14StockHistoryResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\ahistory\x18\x03 \x03(\v2\r.StockHistoryR\ahistory*c\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05FIBER\x10\x01\x12\a\n" +
	"\x03LAN\x10\x02\x12\v\n" +
	"\aROUTERS\x10\x03\x12\f\n" +
	"\bSWITCHES\x10\x04\x12\x0e\n" +
	"\n" +
	"CONNECTORS\x10\x05*J\n" +
	"\x04Unit\x12\x14\n" +
	"\x10UNIT_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06METRES\x10\x01\x12\n" +
	"\n" +
	"\x06PIECES\x10\x02\x12\t\n" +
	"\x05BOXES\x10\x03\x12\t\n" +
	"\x05ROLLS\x10\x04*`\n" +
	"\fChangeReason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aRESTOCK\x10\x01\x12\b\n" +
	"\x04SALE\x10\x02\x12\n" +
	"\n" +
	"\x06DAMAGE\x10\x03\x12\x15\n" +
	"\x11MANUAL_ADJUSTMENT\x10\x042\xe6\x02\n" +
	"\x10InventoryService\x122\n" +
	"\n" +
	"AddProduct\x12\x12.AddProductRequest\x1a\x10.ProductResponse\x122\n" +
	"\n" +
	"GetProduct\x12\x12.GetProductRequest\x1a\x10.ProductResponse\x124\n" +
	"\vUpdateStock\x12\x13.UpdateStockRequest\x1a\x10.ProductResponse\x127\n" +
	"\rDeleteProduct\x12\x15.DeleteProductRequest\x1a\x0f.DeleteResponse\x128\n" +
	"\fListProducts\x12\x14.ListProductsRequest\x1a\x10.ProductResponse0\x01\x12A\n" +
	"\x0fGetStockHistory\x12\x17.GetStockHistoryRequest\x1a\x15.StockHistoryResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_atx_proto_rawDescOnce sync.Once
	file_proto_atx_proto_rawDescData []byte
)

func file_proto_atx_proto_rawDescGZIP() []byte {
	file_proto_atx_proto_rawDescOnce.Do(func() {
		file_proto_atx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_atx_proto_rawDesc), len(file_proto_atx_proto_rawDesc)))
	})
	return file_proto_atx_proto_rawDescData
}

var file_proto_atx_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_atx_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_atx_proto_goTypes = []any{
	(Category)(0),                  // 0: Category
	(Unit)(0),                      // 1: Unit
	(ChangeReason)(0),              // 2: ChangeReason
	(*Product)(nil),                // 3: Product
	(*StockHistory)(nil),           // 4: StockHistory
	(*AddProductRequest)(nil),      // 5: AddProductRequest
	(*GetProductRequest)(nil),      // 6: GetProductRequest
	(*UpdateStockRequest)(nil),     // 7: UpdateStockRequest
	(*DeleteProductRequest)(nil),   // 8: DeleteProductRequest
	(*GetStockHistoryRequest)(nil), // 9: GetStockHistoryRequest
	(*ListProductsRequest)(nil),    // 10: ListProductsRequest
	(*ProductResponse)(nil),        // 11: ProductResponse
	(*DeleteResponse)(nil),         // 12: DeleteResponse
	(*StockHistoryResponse)(nil),   // 13: StockHistoryResponse
}
var file_proto_atx_proto_depIdxs = []int32{
	0,  // 0: Product.category:type_name -> Category
	1,  // 1: Product.unit:type_name -> Unit
	2,  // 2: StockHistory.reason:type_name -> ChangeReason
	0,  // 3: AddProductRequest.category:type_name -> Category
	1,  // 4: AddProductRequest.unit:type_name -> Unit
	2,  // 5: UpdateStockRequest.reason:type_name -> ChangeReason
	3,  // 6: ProductResponse.product:type_name -> Product
	4,  // 7: StockHistoryResponse.history:type_name -> StockHistory
	5,  // 8: InventoryService.AddProduct:input_type -> AddProductRequest
	6,  // 9: InventoryService.GetProduct:input_type -> GetProductRequest
	7,  // 10: InventoryService.UpdateStock:input_type -> UpdateStockRequest
	8,  // 11: InventoryService.DeleteProduct:input_type -> DeleteProductRequest
	10, // 12: InventoryService.ListProducts:input_type -> ListProductsRequest
	9,  // 13: InventoryService.GetStockHistory:input_type -> GetStockHistoryRequest
	11, // 14: InventoryService.AddProduct:output_type -> ProductResponse
	11, // 15: InventoryService.GetProduct:output_type -> ProductResponse
	11, // 16: InventoryService.UpdateStock:output_type -> ProductResponse
	12, // 17: InventoryService.DeleteProduct:output_type -> DeleteResponse
	11, // 18: InventoryService.ListProducts:output_type -> ProductResponse
	13, // 19: InventoryService.GetStockHistory:output_type -> StockHistoryResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_atx_proto_init() }
func file_proto_atx_proto_init() {
	if File_proto_atx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_atx_proto_rawDesc), len(file_proto_atx_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_atx_proto_goTypes,
		DependencyIndexes: file_proto_atx_proto_depIdxs,
		EnumInfos:         file_proto_atx_proto_enumTypes,
		MessageInfos:      file_proto_atx_proto_msgTypes,
	}.Build()
	File_proto_atx_proto = out.File
	file_proto_atx_proto_goTypes = nil
	file_proto_atx_proto_depIdxs = nil
}
